package vandy.psy.schall.meta.model;
// Generated Dec 14, 2016 10:29:33 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudySubject generated by hbm2java
 */
@Entity
@Table(name = "study_subject", catalog = "schalllab")
public class StudySubject implements java.io.Serializable {

	private static final long serialVersionUID = -6533355566969075947L;
	private Integer subjectId;
	private String subjectSpecies;
	private String subjectName;
	private String subjectNameAbbr;
	private String subjectDataDir;
	private String subjectIsActive;
	private Date subjectDob;
	private Date subjectAcquisitionDate;
	private Date subjectDod;
	private String subjectGender;
	private Set<Study> studies = new HashSet<Study>(0);

	public StudySubject() {
	}

	public StudySubject(String subjectSpecies, String subjectName, String subjectNameAbbr, String subjectDataDir,
			String subjectIsActive, Date subjectDob, Date subjectAcquisitionDate, Date subjectDod, String subjectGender,
			Set<Study> studies) {
		this.subjectSpecies = subjectSpecies;
		this.subjectName = subjectName;
		this.subjectNameAbbr = subjectNameAbbr;
		this.subjectDataDir = subjectDataDir;
		this.subjectIsActive = subjectIsActive;
		this.subjectDob = subjectDob;
		this.subjectAcquisitionDate = subjectAcquisitionDate;
		this.subjectDod = subjectDod;
		this.subjectGender = subjectGender;
		this.studies = studies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "subject_id", unique = true, nullable = false)
	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	@Column(name = "subject_species", length = 100)
	public String getSubjectSpecies() {
		return this.subjectSpecies;
	}

	public void setSubjectSpecies(String subjectSpecies) {
		this.subjectSpecies = subjectSpecies;
	}

	@Column(name = "subject_name", length = 50)
	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	@Column(name = "subject_name_abbr", length = 50)
	public String getSubjectNameAbbr() {
		return this.subjectNameAbbr;
	}

	public void setSubjectNameAbbr(String subjectNameAbbr) {
		this.subjectNameAbbr = subjectNameAbbr;
	}

	@Column(name = "subject_data_dir", length = 50)
	public String getSubjectDataDir() {
		return this.subjectDataDir;
	}

	public void setSubjectDataDir(String subjectDataDir) {
		this.subjectDataDir = subjectDataDir;
	}

	@Column(name = "subject_is_active", length = 1)
	public String getSubjectIsActive() {
		return this.subjectIsActive;
	}

	public void setSubjectIsActive(String subjectIsActive) {
		this.subjectIsActive = subjectIsActive;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "subject_dob", length = 10)
	public Date getSubjectDob() {
		return this.subjectDob;
	}

	public void setSubjectDob(Date subjectDob) {
		this.subjectDob = subjectDob;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "subject_acquisition_date", length = 10)
	public Date getSubjectAcquisitionDate() {
		return this.subjectAcquisitionDate;
	}

	public void setSubjectAcquisitionDate(Date subjectAcquisitionDate) {
		this.subjectAcquisitionDate = subjectAcquisitionDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "subject_dod", length = 10)
	public Date getSubjectDod() {
		return this.subjectDod;
	}

	public void setSubjectDod(Date subjectDod) {
		this.subjectDod = subjectDod;
	}

	@Column(name = "subject_gender", length = 10)
	public String getSubjectGender() {
		return this.subjectGender;
	}

	public void setSubjectGender(String subjectGender) {
		this.subjectGender = subjectGender;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studySubject")
	public Set<Study> getStudies() {
		return this.studies;
	}

	public void setStudies(Set<Study> studies) {
		this.studies = studies;
	}

}
