function [ persons ] = PersonPopulate()
%PERSONPOPULATE Populate the Person structure that can be used for
%                updating/inserting data into Person table in MySQL Database
%   Detailed explanation goes here
% %     personList={
% %     {'RH','Rich','Heitz','richard.heitz@gmail.com'},...
% %     {'JC','Jeremiah','Cohen','jeremiah.cohen@gmail.com'},...
% %     {'GW','Geoff','Woodman','geoffrey.f.woodman@vanderbilt.edu'},...
% %     {'BP','Braden','Purcell','braden@nyu.edu'},...
% %     {'DG','David','Godlove','david.godlove@nih.gov'},...
% %     {'UI','Unknown','Investigator','unknown.investigator@schalllab'}...
% %     };
% Jan 19, 2017
    personList={
         {'JS','Jeff','Schall','jeffrey.d.schall@vanderbilt.edu'},...
         {'GW', 'Geoff', 'Woodman','geoffrey.f.woodman@vanderbilt.edu'},...
         {'MS','Michelle','Schall','michelle.schall@vanderbilt.edu'},...
         {'MM','Micala','Maddox','micala.e.maddox@vanderbilt.edu'},...
         {'JE','Jacob','Elsey','jacob.g.elsey@vanderbilt.edu'},...
         {'PM','Paul','Middlebrooks','paul.g.middlebrooks@vanderbilt.edu'},...
         {'TR','Thomas','Reppert','thomas.reppert@vanderbilt.edu'},...
         {'ZR','Zach','Roper','z.roper@vanderbilt.edu'},...
         {'AS','Amirsaman','Sajad','amirsaman.sajad@vanderbilt.edu'},...
         {'WZ','Wolf','Zinke','wolf.zinke@vanderbilt.edu'},...
         {'KL','Kaleb','Lowe','kaleb.a.lowe@vanderbilt.edu'},...
         };
     
    count = 0;
    for ii = length(personList):-1:1
        p = personList{ii};
        person = createPerson(p{1},p{2},p{3},p{4});
       % save individually    
       % persons(count+ii) = person.save;
       persons(count+ii) = person;
    end
    
end

function [ person ] = createPerson(initials,firstname, lastname,email)
   person = Person();
   person.initials = upper(initials);
   person.firstname = firstname;
   person.lastname = lastname;
   person.email = email;
end